name: my_ashaas
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  hexcolor: ^3.0.1
  otp_text_field: ^1.1.3
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  phosphor_flutter: ^2.1.0
  uicons: ^1.0.1
  ionicons: ^0.2.2
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.0
  file_picker: ^9.2.2
  crypto: ^3.0.6
  qr_flutter: ^4.1.0
  http: ^1.3.0
  path: ^1.9.1
  intl: ^0.20.2
  animated_custom_dropdown: ^3.1.1
  flutter_screenutil: ^5.9.3
  country_picker: ^2.0.26
  lottie: ^3.1.2
  cached_network_image: ^3.4.1
  language_info_plus: ^1.0.1
  dropdown_search: ^6.0.2
  country_state_city_pro: ^0.0.3
  csc_picker: ^0.2.7
  country_state_city: ^0.1.6
  country_state_city_picker: ^1.2.8
  dotted_border: ^2.1.0
  device_info_plus: ^12.2.0
  flutter_typeahead: ^5.2.0
  country_code_picker: ^3.4.1
  flutter_launcher_icons: ^0.13.1
  
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ashaas.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/ashaas.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
   



  # fonts:
    # - family: Outfit
    #   fonts:
    #     - asset: assets/fonts/Outfit-Black.ttf
    #     - asset: assets/fonts/Outfit-Bold.ttf
    #     - asset: assets/fonts/Outfit-ExtraBold.ttf
    #     - asset: assets/fonts/Outfit-ExtraLight.ttf
    #     - asset: assets/fonts/Outfit-Light.ttf
    #     - asset: assets/fonts/Outfit-Medium.ttf
    #     - asset: assets/fonts/Outfit-Regular.ttf
    #     - asset: assets/fonts/Outfit-SemiBold.ttf
    #     - asset: assets/fonts/Outfit-Thin.ttf

    # - family: Oxygen
    #   fonts:
    #     - asset: assets/fonts/Oxygen-Bold.ttf
    #     - asset: assets/fonts/Oxygen-Regular.ttf
    #     - asset: assets/fonts/Oxygen-Light.ttf

    # - family: Varela
    #   fonts:
    #     - asset: assets/fonts/VarelaRound-Regular.ttf

    # - family: qs
    #   fonts:
    #     - asset: assets/fonts/QS/Quicksand-Bold.otf
    #     - asset: assets/fonts/QS/Quicksand-Light.otf
    #     - asset: assets/fonts/QS/Quicksand-Medium.otf
    #     - asset: assets/fonts/QS/Quicksand-Regular.otf
    #     - asset: assets/fonts/QS/Quicksand-SemiBold.otf



